export type Article = {
    uri: string;
    content: string;
    source: string;
    dateTime: string;
    urlToImage: string;
    url: string;
    authors: string;
    title: string;
    broadClaim?: string;
    subclaims?: string[];
};

export const dummyArticles: Article[] = [
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-a1b2c3d4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-e5f6g7h8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-i9j0k1l2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-m3n4o5p6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-q7r8s9t0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-u1v2w3x4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-y5z6a7b8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-c9d0e1f2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-g3h4i5j6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-k7l8m9n0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-o1p2q3r4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-s5t6u7v8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-w9x0y1z2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-a3b4c5d6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-e7f8g9h0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-i1j2k3l4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-m5n6o7p8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-q9r0s1t2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-u3v4w5x6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-y7z8a9b0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-c1d2e3f4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-g5h6i7j8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-k9l0m1n2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-o3p4q5r6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-s7t8u9v0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-w1x2y3z4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-a5b6c7d8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-e9f0g1h2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-i3j4k5l6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-m7n8o9p0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-q1r2s3t4',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-u5v6w7x8',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-y9z0a1b2',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-c3d4e5f6',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-g7h8i9j0',
    },
    {
        content: '',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-k1l2m3n4',
    },
];
