export type Article = {
    uri: string;
    content: string;
    source: string;
    dateTime: string;
    urlToImage: string;
    url: string;
    authors: string;
    title: string;
    broadClaim?: string;
    subclaims?: string[];
};

export const dummyArticles: Article[] = [
    {
        content: 'New study shows coffee may improve memory',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-a1b2c3d4',
    },
    {
        content: 'Electric cars outsell gasoline vehicles for the first time',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-e5f6g7h8',
    },
    {
        content: 'Scientists discover new species of deep-sea creature',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-i9j0k1l2',
    },
    {
        content:
            'Global temperatures hit new record high in July sparking wildfire',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-m3n4o5p6',
    },
    {
        content:
            'Artificial intelligence beats human experts in medical diagnosis',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-q7r8s9t0',
    },
    {
        content: 'New renewable energy project powers entire city',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-u1v2w3x4',
    },
    {
        content: 'Breakthrough in quantum computing achieved',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-y5z6a7b8',
    },
    {
        content: 'Ocean cleanup project removes 100 tons of plastic',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-c9d0e1f2',
    },
    {
        content: 'New plant-based meat alternative gains popularity',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-g3h4i5j6',
    },
    {
        content: 'Virtual reality therapy shows promise in treating PTSD',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
        uri: 'uri-k7l8m9n0',
    },
    {
        content: 'Rare solar eclipse visible across North America',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
        uri: 'uri-o1p2q3r4',
    },
    {
        content: 'New gene therapy cures rare childhood disease',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
        uri: 'uri-s5t6u7v8',
    },
    {
        content: 'Autonomous vehicles reduce traffic accidents by 30%',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-w9x0y1z2',
    },
    {
        content: 'Biodegradable packaging solution wins innovation award',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-a3b4c5d6',
    },
    {
        content: 'Worlds largest vertical farm opens in Singapore',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-e7f8g9h0',
    },
    {
        content: 'New antibiotic discovered in soil bacteria',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-i1j2k3l4',
    },
    {
        content: 'Global literacy rates reach all-time high',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-m5n6o7p8',
    },
    {
        content: 'Renewable energy surpasses fossil fuels in power generation',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-q9r0s1t2',
    },
    {
        content: 'Scientists successfully teleport quantum information',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-u3v4w5x6',
    },
    {
        content: 'New coral restoration technique shows promising results',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-y7z8a9b0',
    },
    {
        content: 'First commercial space hotel to open in 2025',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-c1d2e3f4',
    },
    {
        content: 'Novel treatment reverses Alzheimers symptoms in mice',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
        uri: 'uri-g5h6i7j8',
    },
    {
        content: 'Plastic-eating bacteria could revolutionize waste management',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
        uri: 'uri-k9l0m1n2',
    },
    {
        content: 'Worlds first 3D-printed neighborhood completed',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
        uri: 'uri-o3p4q5r6',
    },
    {
        content: 'New satellite system provides global internet coverage',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-s7t8u9v0',
    },
    {
        content: 'Fusion energy breakthrough achieved in laboratory',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-w1x2y3z4',
    },
    {
        content:
            'Record number of endangered species recover from near-extinction',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-a5b6c7d8',
    },
    {
        content: 'Carbon capture technology becomes economically viable',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-e9f0g1h2',
    },
    {
        content: 'Universal flu vaccine shows promising results in trials',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-i3j4k5l6',
    },
    {
        content: 'New desalination technique could solve global water crisis',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-m7n8o9p0',
    },
    {
        content: 'Artificial leaf converts CO2 to fuel efficiently',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-q1r2s3t4',
    },
    {
        content:
            'Brain-computer interface allows paralyzed patients to communicate',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-u5v6w7x8',
    },
    {
        content: 'Sustainable aviation fuel reduces airline emissions by 80%',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-y9z0a1b2',
    },
    {
        content: 'Lab-grown organs successfully transplanted in humans',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
        uri: 'uri-c3d4e5f6',
    },
    {
        content: 'New battery technology doubles electric vehicle range',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
        uri: 'uri-g7h8i9j0',
    },
    {
        content: 'Microplastics discovered in human bloodstream',
        source: '',
        dateTime: '',
        urlToImage: '',
        url: '',
        authors: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
        uri: 'uri-k1l2m3n4',
    },
];
