export type DBArticle = {
    content: string;
    sourceName: string;
    publishedAt: string;
    urlToImage: string;
    url: string;
    author: string;
    title: string;
    broadClaim?: string;
    subclaims?: string[];
};

export const dummyDbArticles: DBArticle[] = [
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 1',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 2',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 1'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 2'],
    },
    {
        content: '',
        sourceName: '',
        publishedAt: '',
        urlToImage: '',
        url: '',
        author: '',
        title: '',
        broadClaim: 'broad claim 3',
        subclaims: ['sub claim 3'],
    },
];
